name: marcelom.github.io
url: http://marcelom.github.io
github_url: https://github.com/marcelom/marcelom.github.io
pygments: true
author: Marcelo Moreira
permalink: /:year/:month/:day/:title.html
exclude: [ README.md ]
